define({
  root: ({
    viewer: {
      common: {
				add: "Add",
				edit: "Edit",
				save: "Save",
				next: "Next",
				cancel: "Cancel",
				back: "Back",
				apply: "Apply",
				close: "Close",
				open: "Open",
				start: "Start",
				loading: "Loading",
				disabledAdmin: "This feature has been disabled by the Administrator",
				width: "Width",
				height: "Height",
				create: "Create",
				yes: "Yes",
				no: "No"
      },
      errors: {
        boxTitle: "An error has occurred",
        invalidConfig: "Invalid configuration",
        invalidConfigNoApp: "Web Mapping Application identifier not specified in index.html.",
        invalidConfigNoAppDev: "No Web Mapping Application identifier is specified in URL parameters (?appid=). In development mode, the appid configuration in index.html is ignored.",
        unspecifiedConfigOwner: "Authorized owner hasn't been configured.",
        invalidConfigOwner: "Story owner is not authorized.",
        invalidApp: "This story cannot be loaded.",
        appLoadingFail: "Something went wrong, the {TPL_NAME} did not load correctly.",
        notConfiguredDesktop: "The story is not configured yet.",
        notConfiguredMobile: "The {TPL_NAME} builder is not supported at this display size. If possible, resize your browser to access the builder or please build your story on a device with a larger screen.",
        notConfiguredMobile2: "Please rotate your device to landscape orientation to use the {TPL_NAME} builder.",
        notAuthorized: "You are not authorized to access this story",
        notAuthorizedBuilder: "You are not authorized to use {TPL_NAME} builder.",
        noViewerIE: "This story is not supported in Internet Explorer before version %VERSION%. %UPGRADE%",
        upgradeBrowser: "<a href='http://browsehappy.com/' target='_blank'>Please update your browser</a>.",
        mapLoadingFail: "Something went wrong, the map did not load correctly.",
        signOut: "Sign Out"
      },
      signin: {
				title: "Authentication is required",
				explainViewer: "Please sign in with an account on %PORTAL_LINK% to access the story.",
				explainBuilder: "Please sign in with an account on %PORTAL_LINK% to configure the story."
			},
      headerFromCommon: {
        storymapsText: "A story map",
        builderButton: "Edit",
        facebookTooltip: "Share on Facebook",
				twitterTooltip: "Share on Twitter",
				bitlyTooltip: "Get a short link",
        share: "Share"
      },
      shareFromCommon: {
        copy: "Copy",
        copied: "Copied",
        open: "Open",
        embed: "Embed in web page",
        embedExplain: "Use the following HTML code to embed the story in a web page.",
        size: "Size (width/height):"
      }
    }
  }),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"hr": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sr": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1,
	"zh-tw": 1
});
