/* eslint quotes: ["error", "double"] */
define({
  root: ({
    commonWebmap: {
      editor: {
        loading: "Please wait while the map editor is loading",
        newTitle: "Create new map",
        editTitle: "Edit map",
        titleLbl: "Title",
        titlePh: "Map title...",
        folderLbl: "The map will be created in the same folder as the story.",
        creating: "Creating the map",
        saving: "Saving the map",
        success: "Map saved",
        successCreate: "Map created",
        cancelTitle: "Discard any unsaved changes?",
        errorDuplicate: "You already have a map with that title",
        errorCreate: "Unable to create map. Please try again.",
        errorSave: "Unable to save map. Please try again.",
        loadFail: "Fatal error, the map editor cannot be loaded",
        notavailable1: "Sorry, creating or editing a map is not supported in Firefox due to a technical limitation. You may want to build your story using a different web browser or use the following workaround.",
        notavailable2: "Sorry, creating or editing a map is not supported since the story map application is not hosted in ${PRODUCT}. Please contact your ArcGIS administrator for more information.",
        notavailable3: "Sorry, creating or editing a map is not supported on this version of Portal for ArcGIS (requires 10.4 or later). Please contact your ArcGIS administrator for more information.",
        notavailable4: "You can create a map using ${MV}, then come back here to add it to your story.",
        notavailable5: "You can edit the map using ${MV}, then come back here and ${APPLY} to see your changes.",
        notavailable6: "map viewer",
        notavailable7: "reload the map",
        close: "Close",
        save: "Save",
        yes: "Yes",
        no: "No"
      }
    }
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "id": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
